//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivoInspeccion
    {
        public int Id { get; set; }
        public int ActivoID { get; set; }
        public string RFID { get; set; }
        public string Serial { get; set; }
        public string Modelo { get; set; }
        public string Material { get; set; }
        public string Marca { get; set; }
        public string Imagen { get; set; }
    
        public virtual Activo Activo { get; set; }
    }
}
