//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EncabezadoFactor
    {
        public int id { get; set; }
        public Nullable<int> Encabezadoid { get; set; }
        public Nullable<int> Factorid { get; set; }
    
        public virtual Encabezado Encabezado { get; set; }
    }
}
