//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelEntities : DbContext
    {
        public ModelEntities()
            : base("name=ModelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccionTomar> AccionTomar { get; set; }
        public virtual DbSet<Activo> Activo { get; set; }
        public virtual DbSet<ActivoInspeccion> ActivoInspeccion { get; set; }
        public virtual DbSet<Cargo> Cargo { get; set; }
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<Certificaciones> Certificaciones { get; set; }
        public virtual DbSet<Curso_Inspector> Curso_Inspector { get; set; }
        public virtual DbSet<Elemento> Elemento { get; set; }
        public virtual DbSet<Elementos> Elementos { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<Encabezado> Encabezado { get; set; }
        public virtual DbSet<EncabezadoFactor> EncabezadoFactor { get; set; }
        public virtual DbSet<Estado> Estado { get; set; }
        public virtual DbSet<EstadoFinal> EstadoFinal { get; set; }
        public virtual DbSet<FactorElemento> FactorElemento { get; set; }
        public virtual DbSet<Factores> Factores { get; set; }
        public virtual DbSet<FichasTec> FichasTec { get; set; }
        public virtual DbSet<FotoEncabezado> FotoEncabezado { get; set; }
        public virtual DbSet<Grupo> Grupo { get; set; }
        public virtual DbSet<Inspeccion> Inspeccion { get; set; }
        public virtual DbSet<Inspeccion_Elemento> Inspeccion_Elemento { get; set; }
        public virtual DbSet<Inspeccion_Elementos> Inspeccion_Elementos { get; set; }
        public virtual DbSet<Inspeccion_inspectores> Inspeccion_inspectores { get; set; }
        public virtual DbSet<InspeccionFactor> InspeccionFactor { get; set; }
        public virtual DbSet<Inspector_certificacion> Inspector_certificacion { get; set; }
        public virtual DbSet<Inspectores> Inspectores { get; set; }
        public virtual DbSet<Linea> Linea { get; set; }
        public virtual DbSet<Pais> Pais { get; set; }
        public virtual DbSet<Resultado> Resultado { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<Sede> Sede { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TipoActivo> TipoActivo { get; set; }
        public virtual DbSet<TSA> TSA { get; set; }
        public virtual DbSet<TSA_Empleado> TSA_Empleado { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Usuario_Sede> Usuario_Sede { get; set; }
        public virtual DbSet<Certificacion_Inspector> Certificacion_Inspector { get; set; }
        public virtual DbSet<Curso> Curso { get; set; }
        public virtual DbSet<Empleado> Empleado { get; set; }
        public virtual DbSet<SedeCategoria> SedeCategoria { get; set; }
        public virtual DbSet<usuario_Rol> usuario_Rol { get; set; }
    }
}
