//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactorElemento
    {
        public int id { get; set; }
        public Nullable<int> Encabezadoid { get; set; }
        public Nullable<int> Factorid { get; set; }
        public Nullable<int> Estadoid { get; set; }
        public string Comentario { get; set; }
    
        public virtual Encabezado Encabezado { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Factores Factores { get; set; }
    }
}
