//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FichasTec
    {
        public int id { get; set; }
        public int Sedeid { get; set; }
        public Nullable<int> ElementoID { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public string Observaciones { get; set; }
        public string Ficha { get; set; }
    }
}
