//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inspeccion_Elemento
    {
        public int id { get; set; }
        public Nullable<int> Inspeccionid { get; set; }
        public Nullable<int> Elementoid { get; set; }
    
        public virtual Elemento Elemento { get; set; }
        public virtual Inspeccion Inspeccion { get; set; }
    }
}
