//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inspector_certificacion
    {
        public int id { get; set; }
        public Nullable<int> Inspectorid { get; set; }
        public Nullable<int> Certificacionid { get; set; }
    
        public virtual Certificaciones Certificaciones { get; set; }
        public virtual Inspectores Inspectores { get; set; }
    }
}
