//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resultado
    {
        public int id { get; set; }
        public Nullable<int> Encabezadoid { get; set; }
        public Nullable<int> EstadoFinalId { get; set; }
        public Nullable<int> AccionTomarId { get; set; }
        public Nullable<int> InspectorID { get; set; }
        public Nullable<System.DateTime> FechaInspeccion { get; set; }
    
        public virtual AccionTomar AccionTomar { get; set; }
        public virtual EstadoFinal EstadoFinal { get; set; }
        public virtual Inspectores Inspectores { get; set; }
    }
}
