//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSA
    {
        public int id { get; set; }
        public string Inspector { get; set; }
        public string RutaPDF { get; set; }
        public Nullable<int> Sedeid { get; set; }
        public Nullable<int> Cursoid { get; set; }
        public string Identificacion { get; set; }
        public Nullable<int> Ano { get; set; }
    }
}
